# Generated by Django 4.2.2 on 2023-07-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('books', models.ManyToManyField(to='book.book')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
